name: Build every monday at 10AM
on:
  schedule:
   - cron: '0 10 * * 1' #Runs at 10AM on Monday, every Monday https://crontab.guru/#0_10_*_*_1

## Use the following for now for a manual run
on:
  workflow_dispatch:
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@master
      with:
        args: "-X POST -H 'Authorization: token ${{ secrets.PAGES_ACCESS_TOKEN }}' -H 'Accept: application/vnd.github.ant-man-preview+json' https://api.github.com/repos/aaronnad/aaronnad.github.io/pages/builds"
