name: Build every hour
# To enable auto builds - disable this below - only when i want to know, this will build this job and the jekyll every hour
#on:
#  schedule:
#   - cron: '0 * * * *'

## Use the following for now for a manual run
## Allowing the workflow to properly create
on:
  workflow_dispatch:
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@master
      with:
        args: "-X POST -H 'Authorization: token ${{ secrets.PAGES_ACCESS_TOKEN }}' -H 'Accept: application/vnd.github.ant-man-preview+json' https://api.github.com/repos/aaronnad/aaronnad.github.io/pages/builds"
